### ISSUE TITLE
Add Support for Sentinl

### ISSUE THREAD

**Issue by ttindell2** [fabric8io/openshift-elasticsearch-plugin#116]
Hi!

I was looking into adding Sentinl plugin into Kibana to allow Tenants to create alerts based on the namespaces logs that are in Elasticsearch. How would I add the indexes (watchers) that Sentinl creates in Elasticsearch to the openshift plugin so that its entries would also support multi-tenancy?? Sentinl does support Searchguard.
  
Sentinl:

https://github.com/sirensolutions/sentinl

**Comment by jcantrill** [comment]
Closing as we are unlikely to add this feature.
