### ISSUE TITLE
create a little README.md file to describe what this project does...

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/openshift-elasticsearch-plugin#3]
... no idea, sounds like fun :) something about an Elasticsearch plugin for OpenShift?

**Comment by jimmidyson** [comment]
Will do soon. It's an experiment to sync up openshift auth policies with search guard ACLs so we can restrict who can see what data in elasticsearch based on openshift authentication.

**Comment by jstrachan** [comment]
ah cool! that sentence sounds a good enough first cut of a README.md :)

**Comment by jimmidyson** [comment]
Done!
