### ISSUE TITLE
Access allows users to see indices in other projects

### ISSUE THREAD

**Issue by richm** [fabric8io/openshift-elasticsearch-plugin#46]
For example, a user in the `test` project can view `logging.*` indices.

**Comment by richm** [comment]
Fixed by https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/47

**Comment by ewolinetz** [comment]
Will need to request kicking off a deployment build so this can be consumed by origin.

**Comment by richm** [comment]
@ewolinetz ok - would like to get https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/44 into a build as well
