### ISSUE TITLE
Read index-pattern data from files rather than hardcoded constants

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#49]
as mentioned in #48

**Comment by richm** [comment]
The kibana index-pattern data is a single line, several thousand byte JSON blob hardcoded into constant strings in the DocumentBuilder class.  Instead, we should read this data from JSON or YAML files.  viaq can generate the elasticsearch index templates as json or yaml files - it could also generate the corresponding kibana index-pattern data and other config data.  https://github.com/ViaQ/elasticsearch-templates/issues/17

**Comment by richm** [comment]
Partially addressed by https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/51 - if using elasticsearch index templates, kibana index patterns are not needed

**Comment by jcantrill** [comment]
Closing as will be fixed by #65
