### ISSUE TITLE
User cache should include token to verify the remote user and token are matched

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#52]
This stems from a request against the 1.X version of the logging setup: http://post-office.corp.redhat.com/archives/openshift-sme/2016-October/msg01163.html but I suspect it applies to the 2.x version as well.

Summary of message:
- Allow users to access ES directly
- Require query to be restricted to same access controls

Analysis from @sosiouxme shows that if the client-certs are leaked:
- A user could access ES first with valid token and remote user name header
- Subsequent requests only require remote user name header and access to indexes are permitted.

Propose to:
- Cache username with token
- Validate username+token match what is cached
- Lookup username if header only has token and match against cache (fail if username/token dont match) (something more shoule happen here)

**Comment by sosiouxme** [comment]
Sounds about right. So I would suggest we actually stop looking at the username header at all, as it's redundant. I don't recall the historical reason for it, so we may find out there was some real need for it. But what should happen when a request comes in with a token is that the plugin

1. checks its cached tokens to see if it already knows this user (if so, it gives back username; proceed with request)
2. for new tokens, do the master API lookup to determine username and level of access (available projects, cluster-admin status) and put the result in the cache

I haven't looked too closely but maybe this just involves putting the username in the ACL cache we already have and pulling it from there as needed. In any case, entries in "the cache" should expire after O(minute) as they do now in the ACL cache. The goal of the cache is to handle bursts of Kibana queries without having to hit the API every time, but keep reasonably current.

**Comment by jcantrill** [comment]
@sosiouxme We look at the username header to reuse the ACL checking that searchguard provides.  I believe it uses the remote proxy header to match against its ACL to determine if you are allowed to see a specific index.

**Comment by ewolinetz** [comment]
The username header has actually become more important recently since it is used with the clusterrole lookup. We still use the token to generate the ACL (by determining the user's access), the clusterrole lookup is done using the Elasticsearch SA, we then check the user list for 'cluster-admins' and/or 'cluster-readers' given the user token.

**Comment by richm** [comment]
Fixed by https://github.com/fabric8io/openshift-elasticsearch-plugin/commit/8abaeedfd69d0be1bdbefa9078a6c9cec2f42a48
