### ISSUE TITLE
Seed Initial Dashboard only once

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#69]
We seed the dashboard everytime we update the user in-memory cache:

https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/master/src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java#L269

Which means we will try to do this everytime the cache expires and a user comes back in.  Seems like that might have some unintended expectations for the user.

**Comment by jcantrill** [comment]
cc @portante @richm @ewolinetz

**Comment by portante** [comment]
@jcantrill, yes, that seems like a bad thing to do.

So we need to seed them when we first encounter the user, but once created, we should not be rebuilding them.

Also, we need a story for reaping users that have been removed.

**Comment by ewolinetz** [comment]
IIRC the reason we did this was to ensure that we always had the correct projects available to the user in cases where access was added/removed

**Comment by jcantrill** [comment]
Closing this issue as we have made various changes to better handle seeding
