### ISSUE TITLE
Invalid method for determining the user's permissions

### ISSUE THREAD

**Issue by enj** [fabric8io/openshift-elasticsearch-plugin#72]
The [isOperationsUser](https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/7291d132c3464610921f93d3a8c96453001d6bfd/src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java#L278-L296) method incorrectly assumes that a user must be directly bound to `cluster-admins` or `cluster-readers` to see the logs.  This is incorrect in two scenarios:

1. The user has rights due to a different binding
2. The user belongs to a group that grants the rights

Instead, the method should perform a [SubjectAccessReview](https://docs.openshift.com/container-platform/latest/rest_api/openshift_v1.html#v1-subjectaccessreview) based on the username and group information (you will probably need to build a reverse index of groups).  The following `SAR` is equivalent to cluster admin:

```json
{
	"kind" : "SubjectAccessReview",
	"apiVersion" : "v1",
	"user" : "<username>",
	"groups" : ["<groups>"],
	"verb" : "*",
	"resource" : "*",
}
```

The following `SAR` could serve as a proxy for `cluster-reader` but that is up to you guys:

```json
{
	"kind" : "SubjectAccessReview",
	"apiVersion" : "v1",
	"user" : "<username>",
	"groups" : ["<groups>"],
	"verb" : "list",
	"resource" : "pods/log",
}
```

cc  @ewolinetz @jcantrill @richm 

@gabemontero may be able to provide guidance on how to perform a `SAR` in Java.

**Comment by enj** [comment]
cc @deads2k @liggitt @smarterclayton in case you guys have any opinions.

**Comment by ewolinetz** [comment]
This is only specific to a user seeing the logs in the `.operations` index. Any normal application logs is allowed based on the user having access to a namespace. E.g. if `oc get projects` would return something (so long as it isn't rolled into the `.operations` index) they would have access to it.

**Comment by enj** [comment]
> This is only specific to a user seeing the logs in the `.operations` index

@ewolinetz We have multiple instances of customers who are trying to see those specific logs but are failing to do so because they belong to a group that grants them cluster admin privileges instead of being directly bound to the role.

**Comment by niconosenzo** [comment]
I just opened BZ  [1446217](https://bugzilla.redhat.com/show_bug.cgi?id=1446217) for this.

**Comment by jcantrill** [comment]
@ewolinetz  Maybe we should do SAR for viewing on all 'operations' namespaces and determine ops user on being able to view them all.  I think we have a list in the plugin that is configurable.

**Comment by deads2k** [comment]
> @ewolinetz Maybe we should do SAR for viewing on all 'operations' namespaces and determine ops user on being able to view them all. I think we have a list in the plugin that is configurable.

If this is about viewing logs, it may be more appropriate to look for the power to get pods/logs across all namespaces  or the one you're interested in.

**Comment by liggitt** [comment]
I think the second SAR is almost right, but should be checking a `get` verb
