### ISSUE TITLE
How to run HttpsProxyClientCertAuthenticatorIntegrationTest ?

### ISSUE THREAD

**Issue by lukas-vlcek** [fabric8io/openshift-elasticsearch-plugin#90]
Is there any documentation about how to successfully run [HttpsProxyClientCertAuthenticatorIntegrationTest.java](https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/cbf1152c9be195cb854aa431c136fe71ca362b08/src/test/java/io/fabric8/elasticsearch/plugin/HttpsProxyClientCertAuthenticatorIntegrationTest.java)?

By default it is [excluded](https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/cbf1152c9be195cb854aa431c136fe71ca362b08/pom.xml#L199) from `mvn test` and if it is run manually then I am getting NPE. I am probably expected to setup some [some ENV vars](https://github.com/fabric8io/openshift-elasticsearch-plugin/blob/cbf1152c9be195cb854aa431c136fe71ca362b08/src/test/java/io/fabric8/elasticsearch/plugin/HttpsProxyClientCertAuthenticatorIntegrationTest.java#L39-L42) first, right? Can we document what is needed for this test to pass?

BTW: Just so you understand why I ask, I am trying to implement [integration tests with Elasticsearch](https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/45) and I may create PR with "real" integration tests with ES, in which case it would make sense to add the above mentioned test into the suite as well and do not exclude it.

**Comment by lukas-vlcek** [comment]
Also I would like to introduce travis tests for this plugin and I would love to see IT be part of this.

**Comment by ewolinetz** [comment]
It seems like for that test to work it'll require some data to be inserted first. I wonder if that should instead be rewritten with mocks so we don't need to be running an actual instance of ES to verify that auth works.

**Comment by richm** [comment]
I think we should have both - unit tests that use mock, and integration tests that use actual ES

**Comment by lukas-vlcek** [comment]
Closing, we now have both unit and integration tests.
See https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/105
